#!/bin/sh

 while read local_ref local_sha remote_ref remote_sha
 do
  if [ "$remote_ref" = "refs/heads/main" ] || [ "$remote_ref" = "refs/heads/development" ]; then
    echo "Direct pushing to '$remote_ref' branch is not allowed. Please use a pull request."
    exit 1
  fi
done